=== Aeliot-Tm/phar.io/data/repository.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://phar.io/repository" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="repository" type="rep:repositoryType" xmlns:rep="https://phar.io/repository"/>
  <xs:complexType name="pharType">
    <xs:sequence>
      <xs:element type="rep:releaseType" name="release" xmlns:rep="https://phar.io/repository"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="releaseType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="rep:signatureType" name="signature" xmlns:rep="https://phar.io/repository"/>
      <xs:element type="rep:hashType" name="hash" xmlns:rep="https://phar.io/repository"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="version" use="required"/>
    <xs:attribute type="xs:string" name="url" use="required"/>
  </xs:complexType>
  <xs:complexType name="signatureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="required" default="gpg"/>
        <xs:attribute type="xs:string" name="url">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Optional attribute. By default ".asc" will be added to the url of the PHAR.
                    If the url of the signature file does not match this pattern, the url can be put here.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="repositoryType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="rep:pharType" name="phar" xmlns:rep="https://phar.io/repository"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="hashType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="required" default="sha-1"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Aeliot-Tm/phar.io/data/phpdox.phive.xml
<?xml version="1.0" ?>
<repository xmlns="https://phar.io/repository"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://phar.io/repository https://phar.io/data/repository.xsd">

    <phar name="phpdox">
        <release version="0.8.1.1" url="https://github.com/theseer/phpdox/releases/download/0.8.1.1/phpdox-0.8.1.1.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="0bc45b960028cd1517f3969a61e4a8e5e30c79f0"/>
        </release>
        <release version="0.8.1" url="https://github.com/theseer/phpdox/releases/download/0.8.1/phpdox-0.8.1.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="b74cbc6c1d20393b46b731efe964095f7e0d68df"/>
        </release>
        <release version="0.8.0" url="https://github.com/theseer/phpdox/releases/download/0.8.0/phpdox-0.8.0.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="5e08ad78f0f8aaa3450151e9ed6bb37c76b0c224"/>
        </release>
    </phar>

</repository>

=== Aeliot-Tm/phar.io/data/phpab.phive.xml
<?xml version="1.0" ?>
<repository xmlns="https://phar.io/repository"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://phar.io/repository https://phar.io/data/repository.xsd">

    <phar name="phpab">
        <release version="1.20.0" url="https://github.com/theseer/Autoload/releases/download/1.20.0/phpab-1.20.0.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="52d12671f6ae24ca1096de34dd6f53ebc58609a6"/>
        </release>
        <release version="1.19.2" url="https://github.com/theseer/Autoload/releases/download/1.19.2/phpab-1.19.2.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="bcd5ff571e7926c944e7e420b32e792766915ff1"/>
        </release>
        <release version="1.19.1" url="https://github.com/theseer/Autoload/releases/download/1.19.1/phpab-1.19.1.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="06c561e6e39062dd5f50826453b10a34ffdd83ee"/>
        </release>
        <release version="1.19.0" url="https://github.com/theseer/Autoload/releases/download/1.19.0/phpab-1.19.0.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="207a566e623a08bbeaabb10066a5c4d6abb85f5c"/>
        </release>
        <release version="1.18.0" url="https://github.com/theseer/Autoload/releases/download/1.18.0/phpab-1.18.0.phar">
            <signature type="gpg"/>
            <hash type="sha-1" value="7a26babdbba1a3e702ec81f9b20bb099d09d5a9b"/>
        </release>
    </phar>

</repository>
